// <auto-generated />
using L1_Zvejyba.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L1_Zvejyba.Migrations
{
    [DbContext(typeof(DemoRestContext))]
    [Migration("20251013171143_Aded cityName")]
    partial class AdedcityName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L1_Zvejyba.Data.Entities.Body", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("cityName");

                    b.ToTable("Bodies");
                });

            modelBuilder.Entity("L1_Zvejyba.Data.Entities.City", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("L1_Zvejyba.Data.Entities.Body", b =>
                {
                    b.HasOne("L1_Zvejyba.Data.Entities.City", "city")
                        .WithMany()
                        .HasForeignKey("cityName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });
#pragma warning restore 612, 618
        }
    }
}
